In [1]:
# Import all the necessary libraries

import numpy as np
import pandas as pd
from datetime import datetime as dt
import itertools
from pathlib import Path

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline

In [2]:
# Read data from the CSV into a dataframe

data_folder = Path('data')

playing_statistics_1 = pd.read_csv(data_folder / 'Season 2000-2001.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_2 = pd.read_csv(data_folder / 'Season 2001-2002.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_3 = pd.read_csv(data_folder / 'Season 2002-2003.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_4 = pd.read_csv(data_folder / 'Season 2003-2004.csv', index_col='Date', parse_dates=True, error_bad_lines=False).reset_index()
playing_statistics_5 = pd.read_csv(data_folder / 'Season 2004-2005.csv', index_col='Date', parse_dates=True, error_bad_lines=False).reset_index()
playing_statistics_6 = pd.read_csv(data_folder / 'Season 2005-2006.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_7 = pd.read_csv(data_folder / 'Season 2006-2007.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_8 = pd.read_csv(data_folder / 'Season 2007-2008.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_9 = pd.read_csv(data_folder / 'Season 2008-2009.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_10 = pd.read_csv(data_folder / 'Season 2009-2010.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_11 = pd.read_csv(data_folder / 'Season 2010-2011.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_12 = pd.read_csv(data_folder / 'Season 2011-2012.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_13 = pd.read_csv(data_folder / 'Season 2012-2013.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_14 = pd.read_csv(data_folder / 'Season 2013-2014.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_15 = pd.read_csv(data_folder / 'Season 2014-2015.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_16 = pd.read_csv(data_folder / 'Season 2015-2016.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_17 = pd.read_csv(data_folder / 'Season 2016-2017.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_18 = pd.read_csv(data_folder / 'Season 2017-2018.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_19 = pd.read_csv(data_folder / 'Season 2018-2019.csv', index_col='Date', parse_dates=True).reset_index()
playing_statistics_20 = pd.read_csv(data_folder / 'Season 2019-2020.csv', index_col='Date', parse_dates=True).reset_index()

b'Skipping line 305: expected 57 fields, saw 72\nSkipping line 306: expected 57 fields, saw 72\nSkipping line 307: expected 57 fields, saw 72\nSkipping line 308: expected 57 fields, saw 72\nSkipping line 309: expected 57 fields, saw 72\nSkipping line 310: expected 57 fields, saw 72\nSkipping line 311: expected 57 fields, saw 72\nSkipping line 312: expected 57 fields, saw 72\nSkipping line 313: expected 57 fields, saw 72\nSkipping line 314: expected 57 fields, saw 72\nSkipping line 315: expected 57 fields, saw 72\nSkipping line 316: expected 57 fields, saw 72\nSkipping line 317: expected 57 fields, saw 72\nSkipping line 318: expected 57 fields, saw 72\nSkipping line 319: expected 57 fields, saw 72\nSkipping line 320: expected 57 fields, saw 72\nSkipping line 321: expected 57 fields, saw 72\nSkipping line 322: expected 57 fields, saw 72\nSkipping line 323: expected 57 fields, saw 72\nSkipping line 324: expected 57 fields, saw 72\nSkipping line 325: expected 57 fields, saw 72\nSkipping line 326: expected 57 fields, saw 72\nSkipping line 327: expected 57 fields, saw 72\nSkipping line 328: expected 57 fields, saw 72\nSkipping line 329: expected 57 fields, saw 72\nSkipping line 330: expected 57 fields, saw 72\nSkipping line 331: expected 57 fields, saw 72\nSkipping line 332: expected 57 fields, saw 72\nSkipping line 333: expected 57 fields, saw 72\nSkipping line 334: expected 57 fields, saw 72\nSkipping line 335: expected 57 fields, saw 72\nSkipping line 336: expected 57 fields, saw 72\nSkipping line 369: expected 57 fields, saw 62\nSkipping line 370: expected 57 fields, saw 62\nSkipping line 371: expected 57 fields, saw 62\nSkipping line 372: expected 57 fields, saw 62\nSkipping line 373: expected 57 fields, saw 62\nSkipping line 374: expected 57 fields, saw 62\nSkipping line 375: expected 57 fields, saw 62\nSkipping line 376: expected 57 fields, saw 62\nSkipping line 377: expected 57 fields, saw 62\nSkipping line 378: expected 57 fields, saw 62\nSkipping line 379: expected 57 fields, saw 62\nSkipping line 380: expected 57 fields, saw 62\nSkipping line 381: expected 57 fields, saw 62\n'
b'Skipping line 337: expected 57 fields, saw 62\nSkipping line 338: expected 57 fields, saw 62\nSkipping line 339: expected 57 fields, saw 62\nSkipping line 340: expected 57 fields, saw 62\nSkipping line 341: expected 57 fields, saw 62\nSkipping line 342: expected 57 fields, saw 62\nSkipping line 343: expected 57 fields, saw 62\nSkipping line 344: expected 57 fields, saw 62\nSkipping line 345: expected 57 fields, saw 62\nSkipping line 346: expected 57 fields, saw 62\nSkipping line 347: expected 57 fields, saw 62\nSkipping line 348: expected 57 fields, saw 62\nSkipping line 349: expected 57 fields, saw 62\nSkipping line 350: expected 57 fields, saw 62\nSkipping line 351: expected 57 fields, saw 62\nSkipping line 352: expected 57 fields, saw 62\nSkipping line 353: expected 57 fields, saw 62\nSkipping line 354: expected 57 fields, saw 62\nSkipping line 355: expected 57 fields, saw 62\nSkipping line 356: expected 57 fields, saw 62\nSkipping line 357: expected 57 fields, saw 62\nSkipping line 358: expected 57 fields, saw 62\nSkipping line 359: expected 57 fields, saw 62\nSkipping line 360: expected 57 fields, saw 62\nSkipping line 361: expected 57 fields, saw 62\nSkipping line 362: expected 57 fields, saw 62\nSkipping line 363: expected 57 fields, saw 62\nSkipping line 364: expected 57 fields, saw 62\nSkipping line 365: expected 57 fields, saw 62\nSkipping line 366: expected 57 fields, saw 62\nSkipping line 367: expected 57 fields, saw 62\nSkipping line 368: expected 57 fields, saw 62\nSkipping line 369: expected 57 fields, saw 62\nSkipping line 370: expected 57 fields, saw 62\nSkipping line 371: expected 57 fields, saw 62\nSkipping line 372: expected 57 fields, saw 62\nSkipping line 373: expected 57 fields, saw 62\nSkipping line 374: expected 57 fields, saw 62\nSkipping line 375: expected 57 fields, saw 62\nSkipping line 376: expected 57 fields, saw 62\nSkipping line 377: expected 57 fields, saw 62\nSkipping line 378: expected 57 fields, saw 62\nSkipping line 379: expected 57 fields, saw 62\nSkipping line 380: expected 57 fields, saw 62\nSkipping line 381: expected 57 fields, saw 62\n'

In [3]:
"""# Parse data as time 

def parse_date(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%y').date()
    

def parse_date_other(date):
    if date == '':
        return None
    else:
        return dt.strptime(date, '%d/%m/%Y').date()

playing_statistics_1.Date = playing_statistics_1.Date.apply(parse_date)    
playing_statistics_2.Date = playing_statistics_2.Date.apply(parse_date)    
playing_statistics_3.Date = playing_statistics_3.Date.apply(parse_date_other)         # The date format for this dataset is different  
playing_statistics_4.Date = playing_statistics_4.Date.apply(parse_date)    
playing_statistics_5.Date = playing_statistics_5.Date.apply(parse_date)    
playing_statistics_6.Date = playing_statistics_6.Date.apply(parse_date)    
playing_statistics_7.Date = playing_statistics_7.Date.apply(parse_date)    
playing_statistics_8.Date = playing_statistics_8.Date.apply(parse_date)    
playing_statistics_9.Date = playing_statistics_9.Date.apply(parse_date)    
playing_statistics_10.Date = playing_statistics_10.Date.apply(parse_date)
playing_statistics_11.Date = playing_statistics_11.Date.apply(parse_date)
playing_statistics_12.Date = playing_statistics_12.Date.apply(parse_date)
playing_statistics_13.Date = playing_statistics_13.Date.apply(parse_date)
playing_statistics_14.Date = playing_statistics_14.Date.apply(parse_date_other)
playing_statistics_15.Date = playing_statistics_15.Date.apply(parse_date_other)
playing_statistics_16.Date = playing_statistics_16.Date.apply(parse_date)
playing_statistics_17.Date = playing_statistics_17.Date.apply(parse_date_other)
playing_statistics_18.Date = playing_statistics_18.Date.apply(parse_date_other)
playing_statistics_19.Date = playing_statistics_19.Date.apply(parse_date_other)
playing_statistics_20.Date = playing_statistics_20.Date.apply(parse_date_other)"""


#Gets all the statistics related to gameplay
                      
columns_req = ['Date','HomeTeam','AwayTeam','FTHG','FTAG','FTR']

playing_statistics_1 = playing_statistics_1[columns_req]                      
playing_statistics_2 = playing_statistics_2[columns_req]
playing_statistics_3 = playing_statistics_3[columns_req]
playing_statistics_4 = playing_statistics_4[columns_req]
playing_statistics_5 = playing_statistics_5[columns_req]
playing_statistics_6 = playing_statistics_6[columns_req]
playing_statistics_7 = playing_statistics_7[columns_req]
playing_statistics_8 = playing_statistics_8[columns_req]
playing_statistics_9 = playing_statistics_9[columns_req]
playing_statistics_10 = playing_statistics_10[columns_req]
playing_statistics_11 = playing_statistics_11[columns_req]   
playing_statistics_12 = playing_statistics_12[columns_req]
playing_statistics_13 = playing_statistics_13[columns_req]
playing_statistics_14 = playing_statistics_14[columns_req]
playing_statistics_15 = playing_statistics_15[columns_req]
playing_statistics_16 = playing_statistics_16[columns_req]
playing_statistics_17 = playing_statistics_16[columns_req]
playing_statistics_18 = playing_statistics_16[columns_req]
playing_statistics_19 = playing_statistics_16[columns_req]
playing_statistics_20 = playing_statistics_16[columns_req]

In [4]:
playing_statistics_1.head()

        Date  HomeTeam       AwayTeam  FTHG  FTAG FTR
0 2000-08-19  Charlton       Man City     4     0   H
1 2000-08-19   Chelsea       West Ham     4     2   H
2 2000-08-19  Coventry  Middlesbrough     1     3   A
3 2000-08-19     Derby    Southampton     2     2   D
4 2000-08-19     Leeds        Everton     2     0   H

In [5]:
# Gets the goals scored agg arranged by teams and matchweek
def get_goals_scored(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        HTGS = playing_stat.iloc[i]['FTHG']
        ATGS = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGS)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGS)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsScored = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsScored[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsScored[i] = GoalsScored[i] + GoalsScored[i-1]
    return GoalsScored

In [6]:
# Gets the goals conceded agg arranged by teams and matchweek
def get_goals_conceded(playing_stat):
    # Create a dictionary with team names as keys
    teams = {}
    for i in playing_stat.groupby('HomeTeam').mean().T.columns:
        teams[i] = []
    
    # the value corresponding to keys is a list containing the match location.
    for i in range(len(playing_stat)):
        ATGC = playing_stat.iloc[i]['FTHG']
        HTGC = playing_stat.iloc[i]['FTAG']
        teams[playing_stat.iloc[i].HomeTeam].append(HTGC)
        teams[playing_stat.iloc[i].AwayTeam].append(ATGC)
    
    # Create a dataframe for goals scored where rows are teams and cols are matchweek.
    GoalsConceded = pd.DataFrame(data=teams, index = [i for i in range(1,39)]).T
    GoalsConceded[0] = 0
    # Aggregate to get uptil that point
    for i in range(2,39):
        GoalsConceded[i] = GoalsConceded[i] + GoalsConceded[i-1]
    return GoalsConceded

In [7]:
def get_gss(playing_stat):
    GC = get_goals_conceded(playing_stat)
    GS = get_goals_scored(playing_stat)
   
    j = 0
    HTGS = []
    ATGS = []
    HTGC = []
    ATGC = []

    for i in range(380):
        ht = playing_stat.iloc[i].HomeTeam
        at = playing_stat.iloc[i].AwayTeam
        HTGS.append(GS.loc[ht][j])
        ATGS.append(GS.loc[at][j])
        HTGC.append(GC.loc[ht][j])
        ATGC.append(GC.loc[at][j])
        
        if ((i + 1)% 10) == 0:
            j = j + 1
        
    playing_stat['HTGS'] = HTGS
    playing_stat['ATGS'] = ATGS
    playing_stat['HTGC'] = HTGC
    playing_stat['ATGC'] = ATGC
    
    return playing_stat

In [14]:
# Apply to each dataset
#playing_statistics_1 = get_gss(playing_statistics_1)
#playing_statistics_2 = get_gss(playing_statistics_2)
#playing_statistics_3 = get_gss(playing_statistics_3)
#playing_statistics_4 = get_gss(playing_statistics_4)
#playing_statistics_5 = get_gss(playing_statistics_5)
playing_statistics_6 = get_gss(playing_statistics_6)
playing_statistics_7 = get_gss(playing_statistics_7)
playing_statistics_8 = get_gss(playing_statistics_8)
playing_statistics_9 = get_gss(playing_statistics_9)
playing_statistics_10 = get_gss(playing_statistics_10)
playing_statistics_11 = get_gss(playing_statistics_11)
playing_statistics_12 = get_gss(playing_statistics_12)
playing_statistics_13 = get_gss(playing_statistics_13)
playing_statistics_14 = get_gss(playing_statistics_14)
#playing_statistics_15 = get_gss(playing_statistics_15)
playing_statistics_16 = get_gss(playing_statistics_16)
playing_statistics_17 = get_gss(playing_statistics_17)
playing_statistics_18 = get_gss(playing_statistics_18)
playing_statistics_19 = get_gss(playing_statistics_19)
playing_statistics_20 = get_gss(playing_statistics_20)

In [20]:
playing_statistics_15.head

        Date    HomeTeam        AwayTeam  FTHG  FTAG FTR
0 2014-08-16     Arsenal  Crystal Palace   2.0   1.0   H
1 2014-08-16   Leicester         Everton   2.0   2.0   D
2 2014-08-16  Man United         Swansea   1.0   2.0   A
3 2014-08-16         QPR            Hull   0.0   1.0   A
4 2014-08-16       Stoke     Aston Villa   0.0   1.0   A

In [37]:
playing_statistics_15.groupby('HomeTeam').mean().T.columns

Index(['Arsenal', 'Aston Villa', 'Burnley', 'Chelsea', 'Crystal Palace',
       'Everton', 'Hull', 'Leicester', 'Liverpool', 'Man City', 'Man United',
       'Newcastle', 'QPR', 'Southampton', 'Stoke', 'Sunderland', 'Swansea',
       'Tottenham', 'West Brom', 'West Ham'],
      dtype='object', name='HomeTeam')